=== anwinged/xml-conversion/config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">

    <xs:element name="items">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="item" type="ItemType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ItemType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="name" type="xs:string"/>
            <xs:element name="limit" type="xs:integer"/>
            <xs:element name="award" type="AwardType"/>
            <xs:element name="alias" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="id" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="AwardType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="resource" type="ResourceType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ResourceType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="type" type="xs:string"/>
            <xs:element name="count" type="xs:integer"/>
            <xs:element name="itemId" type="xs:integer"/>
        </xs:choice>
        <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== anwinged/xml-conversion/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
    <item id="1234">
        <name>Item</name>
        <award>
            <resource type="money">
                <type>money</type>
                <count>100</count>
            </resource>
            <resource type="item">
                <type>item</type>
                <count>2</count>
                <itemId>5</itemId>
            </resource>
        </award>
    </item>
    <item id="1235">
        <name>Item 2</name>
        <alias>item</alias>
        <alias>12345</alias>
    </item>
</items>
